version: "3.1"

services:
  aca:
    image: ghcr.io/nsacyber/hirs/aca:alpha1
    container_name: hirs-aca
    ports:
       - 8443:8443
  hipxe:
    image: ghcr.io/nsacyber/hirs/pypxe-win:alpha1
    container_name: hipxe
    ports:
       - 67:67/udp
       - 68:68/udp
       - 69:69
       - 80:80
    networks:
      hipxe_network:
        ipv4_address: 172.16.1.3
         
networks:
  hipxe_network:
    driver: transparent
    ipam:
      driver: default
      config:
        - subnet: 172.16.1.0/24
          gateway: 172.16.1.1